openapi: 3.0.2
info:
  title: AML API documentation
  version: 1.0.19
servers:
  - url: http://localhost/dev1/ng-crm/yiiapp/backend/web
tags:
  - name: Import
    description: CSV/XLS import
paths:
  $ref: './paths/index.yaml'
components:
  schemas:
    $ref: './schemas/index.yaml'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY #api_key
      in: header
